baseurl = "https://www.generik.dev"
title = "Yash Saksena"
theme = ["hugo-embed-pdf-shortcode","hugo-coder"]
locale = "en-uk"
defaultcontentlanguage = "en"
enableInlineShortcodes = true

[pagination]
pagerSize = 20


[markup.highlight]
style = "aura-theme-dark-soft"

[params]
  author = "Yash Saksena"
  info = "Software Engineer | Tech Artist | Games Generalist "
  description = "Yash's Protfolio"
  keywords = "developer,portfolio,projects"
  avatarurl = "/images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/saksey1/"
[[params.social]]
  name = "Itch"
  icon = "fa-brands fa-itch-io fa-2x"
  weight = 3
  url = "https://generik.itch.io"
[[params.social]]
  name = "Itch"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/yash-saksena-4a9b2616b/"
[[params.social]]
  name = "Resume"
  icon = "fa-regular fa-file fa-2x"
  weight = 3
  url = "../../documents/YashSaksenaResume-23Jul26.pdf"


# Menu links
[[menu.main]]
  name = "Projects"
  weight = 1
  url  = "projects/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"